baseURL = 'https://danielwong0115.github.io/hugo-app/'
languageCode = 'en-us'
title = 'Daniel Wong - Portfolio'
theme = 'PaperMod'

[params]
  description = "Personal portfolio and blog"
  author = "Daniel Wong"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  profileMode.enabled = true
  profileMode.title = "Daniel Wong"
  profileMode.subtitle = "BS/MS in Computer Science, Minor in Data Science @ Northwestern University"
  profileMode.imageUrl = "/hugo-app/images/profile.jpg"
  profileMode.imageTitle = "Daniel Wong"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/danielwong0115"

[[params.profileMode.buttons]]
  name = "Education"
  url = "education"

[[params.profileMode.buttons]]
  name = "Experience"
  url = "experience"

[[params.profileMode.buttons]]
  name = "About"
  url = "about"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "education"
  name = "Education"
  url = "/education/"
  weight = 20

[[menu.main]]
  identifier = "experience"
  name = "Experience"
  url = "/experience/"
  weight = 30

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 40
